quarkus:
  mongodb:
    # TODO Create a custom config by environment
    connection-string: mongodb://root:123456@localhost:27017
    database: go-non-go-matrix
  http:
    root-path: /go-non-go-matrix
  swagger-ui:
    enable: true
    path: /q/swagger-ui
    theme: flattop
    title: Go-Non-Go Matrix API